baseURL: "" 
title: AJ
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: AJ
          url: /about/
          weight: 1
        - name: Research
          url: /research/
          weight: 2
        - name: Thoughts
          url: /blog/
          weight: 3
        - name: Connect
          url: /contact/
          weight: 4

params:
    description: "I am a Research Associate (predoctoral) at Harvard Business School in the Finance and Entrpreneurship units.
    I have a Bachelor's in Data Science, and a Master's in Financial Mathematics. I like to apply data science to machine learning
    solutions for problems in quantitative finance. I currently work on portfolio optimization, data science, and econometrics."
    author: AJ
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: AJ
          subtitle: "I am a Research Associate (predoctoral) at Harvard Business School in the Finance and Entrpreneurship units.
                    I have a Bachelor's in Data Science, and a Master's in Financial Mathematics. I like to apply data scinece to machine learning
                    solutions for problems in quantitative finance. I currently work on portfolio optimization, data science, and econometrics."
          imageUrl: "/AJpicture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: AJ
          buttons:
              - name: AJ
                url: /about/
                weight: 1
              - name: Research
                url: /research/
                weight: 2
              - name: Thoughts
                url: /blog/
                weight: 3
              - name: Connect
                url: /contact/
                weight: 4
    socialIcons:
        - name: CV
          url: /cv.pdf
        - name: Email
          url: mailto:ajena@hbs.edu
        - name: LinkedIn
          url: https://www.linkedin.com/in/aj-jena-13b738172/
        - name: YouTube
          url: https://www.youtube.com/@pmichaillat
        - name: GitHub
          url: https://github.com/pmichaillat?tab=repositories

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "AJ"
      icon: "/favicon-16x16"
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
