baseURL: "https://pascalmichaillat.org/" 
title: Pascal Michaillat
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
pygmentsUseClasses: true

minify:
    disableXML: true
    # minifyOutput: true

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Courses
          url: /courses/
          weight: 2
        - name: LaTeX
          url: /code/
          weight: 3
        - name: Newsletter
          url: https://pmichaillat.substack.com
          weight: 5
        - name: Tags
          url: /tags/
          weight: 4
        # - name: Search
        #   url: search/
        #   weight: 11
        # - name: Archive
        #   url: archives
        #   weight: 7
        # - name: Contact
        #   url: contact/
        #   weight: 8
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    # env: production
    description: "I'm an Associate Professor of Economics at Brown University. I work on unemployment and economic slack, business cycles, macroeconomic policy, metascience."
    author: Pascal Michaillat
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: false
    ShowWordCount: false
    ShowRssButtonInSectionTermList: false
    UseHugoToc: true
    comments: false
    images: ["/apple-touch-icon.png"]
    # mainSections:
    #   - papers
    profileMode:
          enabled: true
          title: Pascal Michaillat
          # subtitle: "Associate Professor of Economics at Brown University"
          subtitle: "Associate Professor of Economics at Brown University. Unemployment and economic slack, business cycles, macroeconomic policy, and some metascience."
          # subtitle: "I'm an Associate Professor of Economics at Brown University. I work on unemployment and economic slack, business cycles, macroeconomic policy, and also in metascience."
          imageUrl: "/picture.jpeg"
          imageWidth: 140
          imageHeight: 140
          imageTitle: Pascal Michaillat
          buttons:
            - name: Papers
              url: /papers/
            # - name: Book
            #   url: papers/
            - name: Courses
              url: /courses/
            - name: LaTeX
              url: /code/
            # - name: Newsletter
            #   url: https://pmichaillat.substack.com
#         title: Pascal Michaillat
#         imageUrl: "/favicon.ico"
#         imageTitle: Purple
#         imageWidth: 80
#         imageHeight: 80
#         buttons:
        # - name: Archive
        #   url: archive
          # weight: 7
        # - name: Search
        #   url: search/
        #   weight: 11
        # - name: Keywords
        #   url: tags/
        #   weight: 10
        # - name: LaTeX
        #   url: latex/
        #   weight: 4
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 9
        # - name: Courses
        #   url: courses/
        #   weight: 6
        # - name: Papers
        #   url: papers/
        #   weight: 1
        # - name: Contact
        #   url: contact/
        #   weight: 8
    label:
      text: "Pascal Michaillat"
      icon: /apple-touch-icon.png
      iconHeight: 16

    # homeInfoParams:
    #     Title: Pascal Michaillat
    #     Content: 
    #       - Associate Professor of Economics at Brown University

    #       - Spring 2023: on leave at UCSD

            # - PaperMod is based on theme [Paper](https://github.com/nanxiaobei/hugo-paper).

    socialIcons:
    - name: CV
      url: "/cv.pdf"
    - name: Google Scholar
      url: "https://scholar.google.com/citations?user=cL23w-4AAAAJ"
    - name: Substack
      url: "https://pmichaillat.substack.com"
    - name: GitHub
      url: "https://github.com/pmichaillat"
    - name: YouTube
      url: "https://www.youtube.com/@pmichaillat"
    - name: Email
      url: "mailto:pascalmichaillat@gmail.com"
    - name: Zoom
      url: "https://brown.zoom.us/my/pascalmichaillat"
    - name: Office Hours
      url: /officehours/
    # - name: Address
    #   url: "https://brown.zoom.us/my/pascalmichaillat"   

    # editPost:
    #     URL: "https://pascalmichaillat.org"
    #     Text: "Permalink" # edit text
    #     appendFilePath: false # to append file path to Edit link

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        disableHLJS: true
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    cover:
        # hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        noClasses: false
        # anchorLineNos: true
        # codeFences: true
        # guessSyntax: true
        # lineNos: true
        # style: monokai

privacy:
    vimeo:
        disabled: true
        simple: true

    twitter:
        disabled: true
        enableDNT: true
        simple: true

    instagram:
        disabled: true
        simple: true

    youtube:
        disabled: true
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
