baseURL: "https://pascalmichaillat.org/" 
title: Pascal Michaillat
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: pmichaillat

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: /papers/
          weight: 1
        - name: Courses
          url: /courses/
          weight: 2
        # - name: Code
        #   url: /code/
        #   weight: 3
        # - name: Newsletter
        #   url: https://pmichaillat.substack.com
        #   weight: 5
        - name: Tags
          url: /tags/
          weight: 4
        # - name: Search
        #   url: search/
        #   weight: 11
        # - name: Archive
        #   url: archives
        #   weight: 7

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    description: "I am an Associate Professor of Economics at Brown University. I work on unemployment, economic slack, business cycles, macroeconomic policy, metascience."
    author: Pascal Michaillat
    googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: light
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    # images: ["/apple-touch-icon.png"]
    math: true
    mainSections:
      - papers
      - courses
    profileMode:
          enabled: true
          title: Pascal Michaillat
          subtitle: "Associate Professor of Economics at Brown University. Unemployment, economic slack, business cycles, macroeconomic policy, and some metascience."
          imageUrl: "/picture.jpeg"
          imageWidth: 140
          imageHeight: 140
          imageTitle: Pascal Michaillat
          buttons:
            - name: Papers
              url: /papers/
            # - name: Book
            #   url: papers/
            - name: Courses
              url: /courses/
            # - name: Code
            #   url: /code/
            - name: Newsletter
              url: https://pmichaillat.substack.com
    socialIcons:
    - name: CV
      url: "/cv.pdf"
    - name: Google Scholar
      url: "https://scholar.google.com/citations?user=cL23w-4AAAAJ"
    - name: Email
      url: "mailto:pascalmichaillat@gmail.com"
    - name: Zoom
      url: "https://brown.zoom.us/my/pascalmichaillat"
    - name: Office Hours
      url: /officehours/
    - name: Substack
      url: "https://pmichaillat.substack.com"
    - name: GitHub
      url: "https://github.com/pmichaillat"
    - name: YouTube
      url: "https://www.youtube.com/@pmichaillat"
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Pascal Michaillat"
      icon: /favicon.ico
      iconHeight: 16

markup:
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# number of characters here:
# title: 70
# description: 120–155
# summary: 270
