baseURL: "https://ajsquestions.github.io/" 
title: AJ
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: /about/
          weight: 1
        - name: Research
          url: /research/
          weight: 2
        - name: Questions
          url: /blog/
          weight: 3
        - name: Connect
          url: /contact/
          weight: 4
        - name: Tags
          url: /tags/
          weight: 5 

params:
    description: "I like to apply Data Science to Machine Learning to create solutions for problems in Quantitative 
    Finance. I currently work on Portfolio Management, Machine Learning, and Data Science related projects."
    author: AJ
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: AJ
          subtitle: "I like to apply Data Science to Machine Learning to create solutions for problems in Quantitative 
          Finance. I currently work on Portfolio Management, Machine Learning, and Data Science related projects."
          imageUrl: "/AJpicture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: AJ
          buttons:
            - name: About
              url: /about/
              weight: 1
            - name: Research
              url: /research/
              weight: 2
            - name: Questions
              url: /blog/
              weight: 3
            - name: Connect
              url: /contact/
              weight: 4
            - name: Tags
              url: /tags/
              weight: 5 
    socialIcons:
        - name: CV
          url: /CV_Aug24.pdf
        - name: Email
          url: mailto:aryaman.jena5000@gmail.com
        - name: LinkedIn
          url: https://www.linkedin.com/in/aj-jena-13b738172/
        - name: GitHub
          url: https://github.com/ajsquestions

    assets:
        disableHLJS: false
        disableScrollBarStyle: false
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "AJ"
      icon: "/favicon-16x16"
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
